### ISSUE TITLE
Exception : Unable to locate Mix file: /vendor/avored/js/avored.js

### ISSUE THREAD

**Issue by 0l1v3r5** [avored/laravel-ecommerce#501]
**Describe the bug**
Exception
Unable to locate Mix file: /vendor/avored/js/avored.js. (View: ~\vendor\avored\framework\resources\views\user\auth\login.blade.php) 

**To Reproduce**
1. composer create-project --prefer-dist avored/laravel-ecommerce avoredshop
2. Set up your Envirionment(.env) file
3. php artisan avored:install 
4. php artisan avored:admin:make
5. Go to http://localhost/admin/login 
6. See error

That's it!

**Comment by indpurvesh** [comment]
I have fixed that bug in `developed` branch.

**Comment by 0l1v3r5** [comment]
OK understood. I guess it will be donated to the branch master

**Comment by indpurvesh** [comment]
@0l1v3r5 

I am not sure but you can give it a try with `developed` branch. 

When you click on `forgot password` on that page this bug should exist and same for when we click on update password from email.

If you want can you please try and if you want you can work on it. just need to update the `script` tag js path only.

**Comment by 0l1v3r5** [comment]
Ok thanks ! Got it

**Comment by 0l1v3r5** [comment]
The problem persists on my side after an update with composer update

**Comment by indpurvesh** [comment]
@0l1v3r5 

Will look at them. I am afraid that you have the older version install. Don't worry i will double check and let you know.

**Comment by 0l1v3r5** [comment]
I was trying to find out why the updates you make are not reflected even when I reinstall the project over and over again and I think I found something. 

In fact the last version on packagist of the [avored/laravel-eccomerce](https://packagist.org/packages/avored/laravel-ecommerce) package is 3.12 while the last release on the [repository on github](https://github.com/avored/laravel-ecommerce) is 3.2.3

So I believe that every time I run the composer create-project --prefer-dist avored/laravel-ecommerce command, it is rather avored / laravel-ecomerce "3.12" that is installed.
